// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSjIn-vO7GqA8oskqpLtpz2AtDWqvTTc',
    appId: '1:578974484653:web:d9913111a033a6fad19e24',
    messagingSenderId: '578974484653',
    projectId: 'turbidity-iot-app',
    authDomain: 'turbidity-iot-app.firebaseapp.com',
    databaseURL: 'https://turbidity-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turbidity-iot-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPfqT2Q4dDcxTWQ-PKQicUt54VRkpvnkY',
    appId: '1:578974484653:android:43fd8efb6a214079d19e24',
    messagingSenderId: '578974484653',
    projectId: 'turbidity-iot-app',
    databaseURL: 'https://turbidity-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turbidity-iot-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmACLJFewuRzzgUdSg1vINTkc_EKYH30',
    appId: '1:578974484653:ios:1bc65a2cdb951167d19e24',
    messagingSenderId: '578974484653',
    projectId: 'turbidity-iot-app',
    databaseURL: 'https://turbidity-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turbidity-iot-app.firebasestorage.app',
    iosBundleId: 'com.example.turbidityIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmACLJFewuRzzgUdSg1vINTkc_EKYH30',
    appId: '1:578974484653:ios:1bc65a2cdb951167d19e24',
    messagingSenderId: '578974484653',
    projectId: 'turbidity-iot-app',
    databaseURL: 'https://turbidity-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turbidity-iot-app.firebasestorage.app',
    iosBundleId: 'com.example.turbidityIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlSjIn-vO7GqA8oskqpLtpz2AtDWqvTTc',
    appId: '1:578974484653:web:980434826a1fc720d19e24',
    messagingSenderId: '578974484653',
    projectId: 'turbidity-iot-app',
    authDomain: 'turbidity-iot-app.firebaseapp.com',
    databaseURL: 'https://turbidity-iot-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turbidity-iot-app.firebasestorage.app',
  );
}
